### PR TITLE
Update AuthWithJWTs.md

### PR DESCRIPTION
**Pull request by lreichert01**
Corrected spelling/grammar.

### CODE REVIEW

**Comment by lreichert01** [comment]
> Hah! Thanks for the close review and corrections!

Welcome.  Still reading about how to use GitHub.  I realized I never put in reviewers to complete the process.  :)

**Comment by Coldarn** [comment]
Ah, right! Now that you've been approved click the "Squash and merge" button at the bottom to commit the changes to master.

**Comment by lreichert01** [comment]
> Ah, right! Now that you've been approved click the "Squash and merge" button at the bottom to commit the changes to master.

I would, but all of my approvals are still blocked for merging.  It states:  The base branch restricts merging to authorized users.  And it doesn't seem to let me in my branches either.

**Comment by Coldarn** [comment]
> I would, but all of my approvals are still blocked for merging. It states: The base branch restricts merging to authorized users. And it doesn't seem to let me in my branches either.

Thanks - I added you and Don to the allowed list of contributors (didn't remember that was a thing, hah!) You should be clear now.

**Pull request merged**
